name: another_workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: pwd and list files
              run: pwd && ls -altr
            - name: Execute shell script
              run: |
                ./ascii.sh