name: another_workflow
on: push
jobs:
    Job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: pwd and list files
              run: pwd && ls -altr
            - name: Execute shell script
              run: |
                chmod +x ascii.sh
                ./ascii.sh
            - name: upload the ascii file
              uses: actions/upload-artifact
              with:
                name: cowsay.txt
                retention-days: 5
                path: .
          