name: another_workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: pwd
              run: pwd && ls -ltr && cd sep2024 && cd sep2024
            - name: Execute shell script
              run: |
                ./ascii.sh