name: another_workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: pwd and list files
              run: pwd && ls -altr
            - name: Execute shell script
              run: |
                chmod +x ascii.sh
                ./ascii.sh
            - name: upload the artifactory
              uses: actions/upload-artifact@v3.2.1-node20
              with:
                # Artifact name
                name: cowsay.txt
                retention-days: 5
          